### ISSUE TITLE
Build error: missing rete_components.pug

### ISSUE THREAD

**Issue by ajaymehul** [htil/neuroflow#1]
I installed all the dependencies using `yarn install`. 
Then `npm run build` results in
```
C:\Users\HTIL\Downloads\neuroflow-block_merge\neuroflow-block_merge\node_modules\pug-load\index.js:27
          throw ex;
          ^

Error: ENOENT: no such file or directory, open 'C:\Users\HTIL\Downloads\neuroflow-block_merge\neuroflow-block_merge\views\rete_components.pug'
    at C:\Users\HTIL\Downloads\neuroflow-block_merge\neuroflow-block_merge\views\index.pug line 29
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Function.read (C:\Users\HTIL\Downloads\neuroflow-block_merge\neuroflow-block_merge\node_modules\pug-load\index.js:69:13)
    at Object.read (C:\Users\HTIL\Downloads\neuroflow-block_merge\neuroflow-block_merge\node_modules\pug\lib\index.js:147:25)
    at C:\Users\HTIL\Downloads\neuroflow-block_merge\neuroflow-block_merge\node_modules\pug-load\index.js:24:25
    at walkAST (C:\Users\HTIL\Downloads\neuroflow-block_merge\neuroflow-block_merge\node_modules\pug-walk\index.js:23:18)
    at C:\Users\HTIL\Downloads\neuroflow-block_merge\neuroflow-block_merge\node_modules\pug-walk\index.js:104:20
    at Array.reduce (<anonymous>)
    at walkAndMergeNodes (C:\Users\HTIL\Downloads\neuroflow-block_merge\neuroflow-block_merge\node_modules\pug-walk\index.js:103:18)
    at walkAST (C:\Users\HTIL\Downloads\neuroflow-block_merge\neuroflow-block_merge\node_modules\pug-walk\index.js:37:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! NeuroBlock@0.0.1 build: `node views/compile.js && node GenerateReteBlocks && webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the NeuroBlock@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HTIL\AppData\Roaming\npm-cache\_logs\2019-07-11T13_58_37_510Z-debug.log ```

**Comment by nicholascioli** [comment]
The newest commit (https://github.com/htil/neuroflow/commit/00d01f5e6057230d09ac096845c1a2683fd00f9e) should fix this.
